from typing import Optional, Protocol
from uuid import UUID

from backend.src.domain.entities import Task


class TaskRepository(Protocol):
    """Port for task persistence operations."""

    async def find_by_id(self, task_id: UUID) -> Optional[Task]: ...

    async def find_by_project(self, project_id: UUID) -> list[Task]: ...

    async def find_by_assignee(self, assignee_id: UUID) -> list[Task]: ...

    async def list_by_project(
        self, project_id: UUID, *, limit: int, offset: int
    ) -> list[Task]: ...

    async def count_by_project(self, project_id: UUID) -> int: ...

    async def save(self, task: Task) -> Task: ...

    async def save_many(self, tasks: list[Task]) -> list[Task]: ...

    async def delete(self, task_id: UUID) -> None: ...
